name: Release 🚀

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*' # Match semantically versioned tags

jobs:
  build-and-release:
    name: Build and Release Network Console 📦
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 🛎️
        uses: actions/checkout@v4

      - name: Set up Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Set Environment Variable 📋
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install Dependencies 📦
        run: |
          HUSKY=0 CYPRESS_INSTALL_BINARY=0 yarn install --prefer-offline --frozen-lockfile

      - name: Build Project 🚧
        run: |
          yarn build
        env:
          CI: false

      - name: Package Build 📦
        run: |
          cd build/ && tar -zcvf ../console.tgz --exclude='./data' .

      - name: Build Project (Embed) 🚧
        run: |
          rm -rf build/
          SKUPPER_CONSOLE_EMBED=true yarn build
        env:
          CI: false

      - name: Package Build (Embed) 📦
        run: |
          cd build/ && tar -zcvf ../console-embed.tgz --exclude='./data' .

      - name: Create Draft Release ✨
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          body: |
            Skupper-console is available as a tar ball:
            - console.tgz
            The embeddable skupper-console is available as a tar ball:
            - console-embed.tgz
            Issues fixed in this release:
            - https://github.com/skupperproject/skupper-console/issues?q=is:issue%20milestone:${{ env.RELEASE_VERSION }}
          draft: true

      - name: Upload Release Asset ⬆️
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./console.tgz
          asset_name: console.tgz
          asset_content_type: application/tar+gzip

      - name: Upload Release Asset (Embed) ⬆️
        id: upload-release-asset-embed
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./console-embed.tgz
          asset_name: console-embed.tgz
          asset_content_type: application/tar+gzip
